#volumes:
#    ocserv-data: {}
services:
  ocserv:
    env_file:
      - ocserv.env
    image: eukhlg/ocserv
    restart: unless-stopped
    container_name: ocserv
    hostname: ocserv
    ports:
      - 443:443/udp
      - 443:443
    volumes:
      # - ocserv-data:/etc/ocserv
      - /opt/ocserv:/etc/ocserv
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
